In [2]:
import torch.nn as nn

# 创建一个线性层
linear_layer = nn.Linear(in_features=10, out_features=5)

# 获取这个层的权重张量
weight_tensor = linear_layer.weight

# 如果层有偏差，也可以获取偏差张量
bias_tensor = linear_layer.bias

print(weight_tensor)
print(bias_tensor)

Parameter containing:
tensor([[ 0.1328,  0.1128,  0.2165,  0.1414, -0.1209, -0.0705, -0.1974, -0.0221,
         -0.1913, -0.2202],
        [ 0.0220, -0.0999, -0.2037,  0.2232, -0.0719, -0.1309,  0.3074, -0.3039,
         -0.2948, -0.0179],
        [ 0.0186, -0.1334,  0.2539,  0.0570,  0.2567, -0.1283,  0.0300, -0.1682,
          0.0515, -0.0956],
        [ 0.0775,  0.0748, -0.2260, -0.1075, -0.0134, -0.0015,  0.1811, -0.1920,
          0.2128,  0.1181],
        [-0.0436,  0.1925, -0.1121,  0.0341, -0.1951, -0.2919, -0.0515,  0.2006,
          0.1914,  0.0451]], requires_grad=True)
Parameter containing:
tensor([0.0061, 0.0630, 0.1417, 0.2799, 0.0940], requires_grad=True)


In [4]:
import torch
a = torch.rand(10, 3, 4)
b = torch.rand(10, 4, 5)
result = torch.matmul(a, b)
print(result)

tensor([[[1.1438, 1.3055, 0.8035, 1.0143, 0.4764],
         [0.7192, 0.6410, 0.4640, 0.5233, 0.2860],
         [1.0350, 1.1551, 0.7767, 0.7677, 0.3313]],

        [[0.4197, 0.6504, 0.8549, 0.5841, 0.6747],
         [0.6886, 1.3599, 1.7349, 1.5172, 1.5506],
         [0.6285, 0.6684, 0.9977, 0.8744, 1.1128]],

        [[1.0565, 0.5090, 1.0541, 0.7350, 0.8123],
         [1.0853, 0.4726, 1.1764, 0.7285, 0.8730],
         [1.3722, 0.5734, 1.3176, 1.0971, 0.9334]],

        [[1.3429, 1.9273, 1.1746, 1.6608, 0.9725],
         [1.3424, 2.0865, 0.9649, 1.7527, 1.1621],
         [1.0327, 1.3081, 0.7048, 1.2313, 0.7364]],

        [[0.7650, 0.3915, 0.4712, 0.4500, 0.3596],
         [1.1740, 0.7228, 0.6044, 1.2556, 0.8664],
         [2.5100, 1.3445, 1.3151, 2.0209, 1.3745]],

        [[0.4740, 0.5039, 0.7798, 0.6015, 0.9773],
         [1.0369, 1.2369, 1.6659, 1.7379, 1.7775],
         [0.3604, 0.3907, 1.3132, 1.1219, 1.1490]],

        [[1.5612, 1.5705, 1.8542, 1.0448, 0.9766],
         [0.3859, 0

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# 定义一个简单的网络模型
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc = nn.Linear(10, 2)  # 假设输入特征维度为10，输出特征维度为2

    def forward(self, x):
        x = self.fc(x)
        return x

# 构建一个对比损失函数
class ContrastiveLoss(nn.Module):
    def __init__(self, margin=1.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, output1, output2, label):
        euclidean_distance = nn.functional.pairwise_distance(output1, output2)
        loss_contrastive = torch.mean((1 - label) * torch.pow(euclidean_distance, 2) +
                                      (label) * torch.pow(torch.clamp(self.margin - euclidean_distance, min=0.0), 2))
        return loss_contrastive

# 实例化模型和损失函数
model = SimpleNN()
criterion = ContrastiveLoss(margin=1.0)
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 假设有一些训练数据
# 这里我们随机生成数据作为示例
# output1 和 output2 是网络的输出，label是一个表示是否相似的标签，1表示相似，0表示不相似
output1 = torch.randn(10, 10)  # 假设有10个样本，每个样本10个特征
output2 = torch.randn(10, 10)
print(output2)
labels = torch.randint(0, 2, (10,))
print(labels)

# 训练模型
for epoch in range(5):  # 训练5个epoch
    optimizer.zero_grad()
    out1 = model(output1)
    out2 = model(output2)
    loss = criterion(out1, out2, labels)
    loss.backward()
    optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')


tensor([[ 0.1003,  0.0381, -0.6002,  0.4353,  0.3966,  1.4162,  0.4074, -0.1586,
         -1.8882, -0.5203],
        [-1.9297, -1.1979, -0.7297,  1.3755,  0.2209, -0.5329,  0.5461,  1.3155,
         -0.4006,  1.1193],
        [ 1.2182, -1.1465, -0.3906,  0.7033, -0.2705,  0.3169, -1.1857,  0.1887,
          0.8311, -0.1330],
        [-0.7727,  0.3928,  0.8871,  0.7755,  0.2137, -0.4681, -1.2016,  1.6911,
         -0.7082,  0.3101],
        [-1.6079,  0.0609, -1.3850, -0.5055,  0.5591,  0.5418, -0.8964,  0.5556,
          0.0289, -2.2731],
        [-1.0700,  0.2935,  0.2194, -0.4397, -2.0607, -1.3887, -0.4099,  1.2036,
          1.3818, -0.4682],
        [ 0.0687,  0.4978,  0.2082,  0.6657, -0.4936, -0.7826, -0.0898,  0.7686,
         -0.7218,  0.3256],
        [-0.5222,  0.1381, -0.6129, -0.9769,  0.6399, -0.2060, -0.1598, -2.2684,
         -0.5007, -1.8598],
        [ 0.3291,  0.0232,  0.7342,  1.8856,  1.1988,  0.9191,  0.7936,  0.4591,
         -1.0628, -0.4688],
        [-0.2844, -